import Speak = require("sitecore/shell/client/Speak/Assets/lib/core/1.2/SitecoreSpeak");

class ActionManager extends Speak.ControlBase {
  // #region Public Properties
  // This region was generated by a tool. Changes to this region may cause incorrect behavior and will be lost if the code is regenerated.
  public Category: string;
  public Prefix: string;
  // #endregion

  private prefix;

  initialized() {
    this.app.on("all", this.fire, this);

    this.prefix = (this.Prefix || "action") + ":";
  }

  fire(data, args) {
    if (data.substring(0, this.prefix.length) != this.prefix) {
      return;
    }

    var category = this.Category || "client";

    var script = "/-/speak/v1/" + category + "/" + data.substr(7) + ".js";

    require([script], (action) => {
        action(args);
      }
    );
  }
}

Sitecore.component(ActionManager, "ActionManager");
